// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: direct_messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelMemberParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const findExistingDM = `-- name: FindExistingDM :one
SELECT c.id FROM channels c
JOIN channel_members cm1 ON cm1.channel_id = c.id AND cm1.user_id = $1
JOIN channel_members cm2 ON cm2.channel_id = c.id AND cm2.user_id = $2
WHERE c.kind = 'dm'
LIMIT 1
`

type FindExistingDMParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) FindExistingDM(ctx context.Context, arg FindExistingDMParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, findExistingDM, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChannelMembers = `-- name: GetChannelMembers :many
SELECT u.id, u.username FROM users u
JOIN channel_members cm ON cm.user_id = u.id
WHERE cm.channel_id = $1
`

type GetChannelMembersRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) GetChannelMembers(ctx context.Context, channelID uuid.UUID) ([]GetChannelMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMembersRow
	for rows.Next() {
		var i GetChannelMembersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDMs = `-- name: GetUserDMs :many
SELECT
    c.id         AS channel_id,
    u.id         AS other_user_id,
    u.username   AS other_username
FROM channels c
JOIN channel_members cm_self  ON cm_self.channel_id  = c.id AND cm_self.user_id  = $1
JOIN channel_members cm_other ON cm_other.channel_id = c.id AND cm_other.user_id != $1
JOIN users u ON u.id = cm_other.user_id
WHERE c.kind = 'dm'
ORDER BY c.created_at DESC
`

type GetUserDMsRow struct {
	ChannelID     uuid.UUID `json:"channel_id"`
	OtherUserID   uuid.UUID `json:"other_user_id"`
	OtherUsername string    `json:"other_username"`
}

func (q *Queries) GetUserDMs(ctx context.Context, userID uuid.UUID) ([]GetUserDMsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserDMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserDMsRow
	for rows.Next() {
		var i GetUserDMsRow
		if err := rows.Scan(&i.ChannelID, &i.OtherUserID, &i.OtherUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS (
    SELECT 1 FROM channel_members
    WHERE channel_id = $1 AND user_id = $2
) AS is_member
`

type IsChannelMemberParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
