// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, id)
	return err
}

const getFriends = `-- name: GetFriends :many
SELECT
    f.id AS friendship_id,
    CASE
        WHEN f.requester_id = $1 THEN f.addressee_id
        ELSE f.requester_id
    END AS friend_id,
    u.username AS friend_username,
    f.status
FROM friendships f
JOIN users u ON u.id = CASE
    WHEN f.requester_id = $1 THEN f.addressee_id
    ELSE f.requester_id
END
WHERE (f.requester_id = $1 OR f.addressee_id = $1)
  AND f.status = 'accepted'
ORDER BY u.username ASC
`

type GetFriendsRow struct {
	FriendshipID   uuid.UUID   `json:"friendship_id"`
	FriendID       interface{} `json:"friend_id"`
	FriendUsername string      `json:"friend_username"`
	Status         string      `json:"status"`
}

func (q *Queries) GetFriends(ctx context.Context, requesterID uuid.UUID) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.FriendID,
			&i.FriendUsername,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
LIMIT 1
`

type GetFriendshipParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendship, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at FROM friendships WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id uuid.UUID) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFriendRequests = `-- name: GetPendingFriendRequests :many
SELECT f.id, f.requester_id, u.username AS requester_username, f.created_at
FROM friendships f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type GetPendingFriendRequestsRow struct {
	ID                uuid.UUID `json:"id"`
	RequesterID       uuid.UUID `json:"requester_id"`
	RequesterUsername string    `json:"requester_username"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) GetPendingFriendRequests(ctx context.Context, addresseeID uuid.UUID) ([]GetPendingFriendRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingFriendRequestsRow
	for rows.Next() {
		var i GetPendingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.RequesterUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friendships (requester_id, addressee_id)
VALUES ($1, $2)
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, updateFriendshipStatus, arg.Status, arg.ID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
