// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChannelInvite = `-- name: CreateChannelInvite :one
INSERT INTO channel_invites (channel_id, inviter_id, invitee_id)
VALUES ($1, $2, $3)
RETURNING id, channel_id, inviter_id, invitee_id, status, created_at
`

type CreateChannelInviteParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	InviterID uuid.UUID `json:"inviter_id"`
	InviteeID uuid.UUID `json:"invitee_id"`
}

func (q *Queries) CreateChannelInvite(ctx context.Context, arg CreateChannelInviteParams) (ChannelInvite, error) {
	row := q.db.QueryRowContext(ctx, createChannelInvite, arg.ChannelID, arg.InviterID, arg.InviteeID)
	var i ChannelInvite
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.InviterID,
		&i.InviteeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelInvite = `-- name: GetChannelInvite :one
SELECT id, channel_id, inviter_id, invitee_id, status, created_at FROM channel_invites WHERE id = $1
`

func (q *Queries) GetChannelInvite(ctx context.Context, id uuid.UUID) (ChannelInvite, error) {
	row := q.db.QueryRowContext(ctx, getChannelInvite, id)
	var i ChannelInvite
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.InviterID,
		&i.InviteeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getExistingInvite = `-- name: GetExistingInvite :one
SELECT id FROM channel_invites
WHERE channel_id = $1 AND invitee_id = $2 AND status = 'pending'
LIMIT 1
`

type GetExistingInviteParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	InviteeID uuid.UUID `json:"invitee_id"`
}

func (q *Queries) GetExistingInvite(ctx context.Context, arg GetExistingInviteParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getExistingInvite, arg.ChannelID, arg.InviteeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPendingInvites = `-- name: GetPendingInvites :many
SELECT
    ci.id,
    ci.channel_id,
    c.name      AS channel_name,
    u.username  AS inviter_username,
    ci.created_at
FROM channel_invites ci
JOIN channels c ON c.id = ci.channel_id
JOIN users u    ON u.id = ci.inviter_id
WHERE ci.invitee_id = $1 AND ci.status = 'pending'
ORDER BY ci.created_at DESC
`

type GetPendingInvitesRow struct {
	ID              uuid.UUID `json:"id"`
	ChannelID       uuid.UUID `json:"channel_id"`
	ChannelName     string    `json:"channel_name"`
	InviterUsername string    `json:"inviter_username"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) GetPendingInvites(ctx context.Context, inviteeID uuid.UUID) ([]GetPendingInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvites, inviteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingInvitesRow
	for rows.Next() {
		var i GetPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ChannelName,
			&i.InviterUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInviteStatus = `-- name: UpdateInviteStatus :one
UPDATE channel_invites SET status = $1
WHERE id = $2
RETURNING id, channel_id, inviter_id, invitee_id, status, created_at
`

type UpdateInviteStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (ChannelInvite, error) {
	row := q.db.QueryRowContext(ctx, updateInviteStatus, arg.Status, arg.ID)
	var i ChannelInvite
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.InviterID,
		&i.InviteeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
