// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addChannelMemberWithRole = `-- name: AddChannelMemberWithRole :exec
INSERT INTO channel_members (channel_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddChannelMemberWithRoleParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddChannelMemberWithRole(ctx context.Context, arg AddChannelMemberWithRoleParams) error {
	_, err := q.db.ExecContext(ctx, addChannelMemberWithRole, arg.ChannelID, arg.UserID, arg.Role)
	return err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO channels (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at, kind
`

type CreateChannelParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.UUID      `json:"created_by"`
}

// queries/channels.sql
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.Description, arg.CreatedBy)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (channel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, channel_id, user_id, content, created_at
`

type CreateMessageParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
}

// queries/messages.sql
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createMessageWithID = `-- name: CreateMessageWithID :one
INSERT INTO messages (id, channel_id, user_id, content, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel_id, user_id, content, created_at
`

type CreateMessageWithIDParams struct {
	ID        uuid.UUID `json:"id"`
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMessageWithID(ctx context.Context, arg CreateMessageWithIDParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessageWithID,
		arg.ID,
		arg.ChannelID,
		arg.UserID,
		arg.Content,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createPrivateChannel = `-- name: CreatePrivateChannel :one
INSERT INTO channels (name, description, created_by, kind)
VALUES ($1, $2, $3, 'private')
RETURNING id, name, description, created_by, created_at, kind
`

type CreatePrivateChannelParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreatePrivateChannel(ctx context.Context, arg CreatePrivateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createPrivateChannel, arg.Name, arg.Description, arg.CreatedBy)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, description, created_by, created_at, kind FROM channels
WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getChannelMemberRole = `-- name: GetChannelMemberRole :one
SELECT role FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelMemberRoleParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetChannelMemberRole(ctx context.Context, arg GetChannelMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getChannelMemberRole, arg.ChannelID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getMessagesByChannel = `-- name: GetMessagesByChannel :many
SELECT
    m.id,
    m.content,
    m.created_at,
    m.channel_id,
    u.id       AS user_id,
    u.username AS username
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1
ORDER BY m.created_at ASC
LIMIT $2
`

type GetMessagesByChannelParams struct {
	ChannelID uuid.UUID `json:"channel_id"`
	Limit     int32     `json:"limit"`
}

type GetMessagesByChannelRow struct {
	ID        uuid.UUID `json:"id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	ChannelID uuid.UUID `json:"channel_id"`
	UserID    uuid.UUID `json:"user_id"`
	Username  string    `json:"username"`
}

func (q *Queries) GetMessagesByChannel(ctx context.Context, arg GetMessagesByChannelParams) ([]GetMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannel, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChannelRow
	for rows.Next() {
		var i GetMessagesByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.ChannelID,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChannels = `-- name: GetUserChannels :many
SELECT c.id, c.name, c.description, c.created_by, c.created_at, c.kind FROM channels c
WHERE c.kind = 'public'
UNION
SELECT c.id, c.name, c.description, c.created_by, c.created_at, c.kind FROM channels c
JOIN channel_members cm ON cm.channel_id = c.id
WHERE c.kind = 'private' AND cm.user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetUserChannels(ctx context.Context, userID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getUserChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, description, created_by, created_at, kind FROM channels
ORDER BY name ASC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
