// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// queries/channels.sql
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	// queries/messages.sql
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error)
	GetMessagesByChannel(ctx context.Context, arg GetMessagesByChannelParams) ([]GetMessagesByChannelRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListChannels(ctx context.Context) ([]Channel, error)
}

var _ Querier = (*Queries)(nil)
